apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: seal-sidecar
    image: ko://github.com/davidhadas/seal-control/cmd/seal-sidecar
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: shared-volume
        mountPath: /seal
  initContainers:
  - name: seal-init
    image: ko://github.com/davidhadas/seal-control/cmd/seal-init
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: shared-volume
        mountPath: /seal
  volumes:
    - name: shared-volume
      emptyDir: {}