apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      imagePullSecrets:
      - name: dhadas-kube-pull-secret
      containers:
      - name: ubuntu
        image: quay.io/dhadas/wrap-ubuntu
        command: ["sleep"]
        args: ["123456"]
        envFrom:
        - secretRef:
            name: secret-basic-auth
        - configMapRef:
            name: game-config
        env: 
        - name: WRAP_DEBUG
          value: "True"
        - name: DEMO_STRING
          value: "This is a demo string"
        - name: DEMO_NUM
          value: "42" 
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-basic-auth
              key: username
        - name: PLAYER_INITIAL_LIVES 
          valueFrom:
            configMapKeyRef:
              name: game-config           # The ConfigMap this value comes from.
              key: player_initial_lives # The key to fetch.
        - name: GATE_PROPETRIES_ENV
          valueFrom:
            configMapKeyRef:
              name: game-config           # The ConfigMap this value comes from.
              key: game.properties # The key to fetch.
        volumeMounts:
        - name: hack-volume
          mountPath: /hack
        - name: cm-volume
          mountPath: /sealed/cm
        - name: secret-volume
          readOnly: true
          mountPath: "/sealed/etc/secret-volume"
      volumes:
      - name: hack-volume
        persistentVolumeClaim:
          claimName: silver-pvc
      - name: cm-volume
        configMap:
          name: game-config
      - name: secret-volume
        secret:
          secretName: secret-basic-auth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true 
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth
