kind: Role
metadata:
  name: my-reader
rules:
  - apiGroups:
      - ""
    resources:
      - ConfiMap
    verbs: 
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-reader
subjects:
  - kind: ServiceAccount
    name: my-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-reader
